### ISSUE TITLE
Frequent prompts for disconnected

### ISSUE THREAD

**Issue by cnZary** [Rexios80/Health-Data-Server-Overlay#62]
**Did you try [these troubleshooting steps?](https://github.com/Rexios80/Health-Data-Server-Overlay/wiki/Troubleshooting)**
Yes/No (If you say no please provide an explanation)
No,This fault is not related to the list
**Hardware/Software**
- iPhone: iPhone SE 2020
- iOS: 15.4(19E241)
- Apple Watch: Series 7 45mm
- watchOS: 8.5(19T242)
- Windows:  Windows 10 21H2 19044.1586
- App: 11.6(1)
- Server: 11.0.0+8

**To Reproduce**
1. Upgrade watchOS to 8.5
2. open HDS,click start
3. hds_overlay hds_overlay Prompt to disconnected and connected now

**Expected behavior**
Keep the link and do not report an error

**Screenshots**
![Snipaste_2022-03-31_21-39-58](https://user-images.githubusercontent.com/5895098/161069683-86af69f4-e63b-474c-a3a8-d7d9e29f7cfa.jpg)
**Additional context**

**Comment by Rexios80** [comment]
Also if you only need heart rate you could go through the cloud for free and avoid the issue entirely

**Comment by mattbisme** [comment]
I'm running into this same issue. Cloud is affected as well; watchOS 8.5.1 didn't seem to fix anything either. Accuracy is definitely affected by this issue. Although it's rare that the heart rate in the display will fallback to a dash ("—"), it does happen occasionally. 

Basically, the currently displayed heart rate will just kind of "hang" on the last seen BPM until the connection reestablishes and receives and updated value.

**Comment by Rexios80** [comment]
Can't reproduce the issue with the cloud. Even if the watch is disconnecting, the overlay can't tell through the cloud. But receiving data doesn't seem to be affected.

<img width="300" alt="Screen Shot 2022-04-04 at 3 40 53 PM" src="https://user-images.githubusercontent.com/7896519/161619616-e6979743-d1a8-4673-9b2b-7424764de247.png">

**Comment by Rexios80** [comment]
I figured it out. It looks like Apple broke websocket pinging with URLSessionWebSocketTask which was causing the watch to force reconnect every 15 seconds... So now I'm working on migrating to another websocket client solution which should hopefully fix this issue.

This would also explain why my server was getting hammered by auth events 🙃

**Comment by Rexios80** [comment]
This should be fixed in 12.0+4

This build is currently on TestFlight if you want to get it early: https://testflight.apple.com/join/hG4FkmZ4

**Comment by cnZary** [comment]
Incidentally, this solution is still not available on iOS16+watchOS9
Although they are not released :)
Unfortunately I can't test in watchOS 8.5 right now

**Comment by Rexios80** [comment]
I'm going to sit on the watchOS 9 issue until it's closer to release. Hopefully apple fixes it by then.

**Comment by Rexios80** [comment]
The watchOS 9 issue is resolved with the RTD Fallback feature in the watch app version currently on TestFlight
